// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWgC56bwPJvw7KjL8o7iM9ya6VtBvawQc',
    appId: '1:567173278499:web:86b63081e0bb2b2f797a96',
    messagingSenderId: '567173278499',
    projectId: 'chat-app-phone',
    authDomain: 'chat-app-phone.firebaseapp.com',
    storageBucket: 'chat-app-phone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMURFmhiqS_FuZDtEN_6xCErbXsnpnWRM',
    appId: '1:567173278499:android:47e7587577f67a8c797a96',
    messagingSenderId: '567173278499',
    projectId: 'chat-app-phone',
    storageBucket: 'chat-app-phone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjsEEJiR_IfX6MzWWs59nyh0-m3r58Igs',
    appId: '1:567173278499:ios:195d73ada821538a797a96',
    messagingSenderId: '567173278499',
    projectId: 'chat-app-phone',
    storageBucket: 'chat-app-phone.appspot.com',
    iosBundleId: 'com.rahamat.chatAppPhone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjsEEJiR_IfX6MzWWs59nyh0-m3r58Igs',
    appId: '1:567173278499:ios:dd3675bc428c627e797a96',
    messagingSenderId: '567173278499',
    projectId: 'chat-app-phone',
    storageBucket: 'chat-app-phone.appspot.com',
    iosBundleId: 'com.rahamat.chatAppPhone.RunnerTests',
  );
}
